### ISSUE TITLE
error in generating protein sequence

### ISSUE THREAD

**Issue by TDDB-limagrain** [ikmb/vcf2prot#1]
dear @HeshamElAbd,
thank you very much for developing this very promising tool.
I successfully ran it on my infrastructure, but faced some problem for one case. It seems to complain about difficult cases with small indels. Please find attached the files. Would you be able to run it and check whether there is room for improvement regarding such case?
The program returns me this error `Critical error was encountered: for transcript: Solyc02g062560 the following mutations were observed` with a list of positions and instructions.

Thanks a lot!

Best regards,

Thomas

[test.zip](https://github.com/ikmb/vcf2prot/files/9308324/test.zip)

**Comment by HeshamElAbd** [comment]
Hi Thomas, 

Thank you very much for your kind words and I am really happy that you found the tool useful. 

Could you please tell me which version you are using? I tried to replicate the problem with the latest version:  '0.1.4' and it worked out smoothly. 

This version can be downloaded from the bins directory on the cpu_only branch. I would also add it the bins directory on the main branch and update the release of the project. 

Thanks a lot for your time and I am truly looking forward to your feedback, 

Best Regards, 
Hesham

**Comment by TDDB-limagrain** [comment]
Thank you very much for your answer.
I was indeed using version 0.1.2.
But after re-cloning from the cpu_only branch or even by downloading the bins directly, I was unable to get version 0.1.4. I am probably doing something wrong! I will try to dive deeper into the problem.

**Comment by TDDB-limagrain** [comment]
Hi Hesham,
I was finally able to work with my example after using the Linux binaries available in the current release.
(It seems however that typing `vcf2prot_linux --help` still returns `vcf2prot 0.1.2`.)

Thank you very much for the help!

Thomas

**Comment by HeshamElAbd** [comment]
Hi Tomas (@TDDB-limagrain ) 

Please, it is really my pleasure!!! and I am really glad that everything went smooth. I am really sorry for any inconvenience caused, I will dig deeper into this and will harmonise and tide up the versioning of the tool.

Thanks a lot for using the tool and for your feedback to make it better, please let me know if I there is anything else that needs to be addressed or if there is any feature you would like to have.  Also, if the issue has been solved, please feel free to close the issue. 

All the best, 
Hesham

**Comment by TDDB-limagrain** [comment]
Thanks Hesham,
I am closing this issue and re-opening a new one for little problem related to protein identifier format!
Best regards,

Thomas
